# ── Base de datos Supabase ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xopwdbjbyckxdtdhcljr
spring.datasource.password=GatitomalO23@@
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ── Zona horaria Lima ──────────────────────────────────────────
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.time-zone=America/Lima

# ── Thymeleaf ──────────────────────────────────────────────────
spring.thymeleaf.check-template-location=false

# ── Telegram ───────────────────────────────────────────────────
telegram.bot.token=8641316677:AAGWx3a5CMLr-NeGDkJ4f4KpmNrtdHeA0fI
telegram.bot.chatId=8731096128

# ── Puerto ─────────────────────────────────────────────────────
server.port=${PORT:8080}